# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Declare git user info
        run: |
        git config --global user.name 'rxliuli'
        git config --global user.email 'rxliuli@gmail.com'
      - name: build DataList
        run: |
        npm i
        npm run build
      - name: Commit report
        run: |
        git commit -am "build DataList.json"
        git push
