# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build DataList
        - run: yarn 
        - run: yarn build
      - name: Commit report
        - run: git config --global user.name 'rxliuli' 
        - run: git config --global user.email 'rxliuli@gmail.com' 
        - run: git add -A 
        - run: git commit -am "build DataList.json" 
        - run: git push
